### PR TITLE
fix: Add mappings from stackName to topic to fix an issue with messages not rendering

### LINKED ISSUE #57: Web Console not displaying events after migrating to v2
I often use the serverless-spy web console to debug my app. This worked perfectly in v1.

However, after migrating to v2, the web console no longer displays any events when I run my tests. The console itself is running correctly, and I can see connection logs on my terminal, but no events are shown on the page. There are no errors or warnings in the logs that might indicate what is causing the issue.

I'm using nodejs 20 for my lambdas and serverless-spy 2.3.3.
Are there any new configurations or changes needed to ensure the console receives and displays events in v2 ? Can you verify if this issue is reproducible on your end ?

### PR DESCRIPTION
**Pull request by Lewenhaupt**
Fixes #57

### CODE REVIEW

File: cli/webServerlessSpy.ts [hunk 1]
```diff
@@ -120,6 +122,24 @@ function run() {
...
+    return (
+      stackList &&
+      stackList?.length > 1 &&
+      stackNameToTopicMappings &&
+      Object.values(stackNameToTopicMappings).length
+    );
+  }
+
+  async function loadStackNameToTopicMappings() {
+    const response = await fetch('/stackTopicMappings');
```
Comment (ServerlessLife) [inline cli/webServerlessSpy.ts:135]: Where is this endpoint implemented?

File: src/ServerlessSpy.ts [hunk 2]
```diff
@@ -103,6 +103,10 @@ export class ServerlessSpy extends Construct {
       key: 'ServerlessSpyWsUrl',
       value: `${this.iotEndpoint}/${rootStack}`,
     });
+    new CfnOutput(this, 'ServerlessSpyTopic', {
```
Comment (ServerlessLife) [inline src/ServerlessSpy.ts:106]: > You: Yeah we could do it that way, but that would break it if we changed the format of the IoT topic used and didn't update the message. I think this would be more reliable?

I really do not see the reason for the additional output. Back then, when you were developing the IoT solution, we combined both values just for the purpose of avoiding additional output. When `ServerlessSpyWsUrl` is used, it is split into the actual IoT endpoint and the stack and used separately. The whole "url" is actually not used at all.

File: cli/webServerlessSpy.ts (hunk 1 above)
Comment (Lewenhaupt) [reply cli/webServerlessSpy.ts:135]: It was supposed to be in cli.ts but I must have missed committing it? Will fix in a sec.

File: src/ServerlessSpy.ts (hunk 2 above)
Comment (Lewenhaupt) [reply src/ServerlessSpy.ts:106]: I think the reason we combined them in the output was to avoid users having to refactor their tests because the listener required the parameter so we opted for making it backwards compatible.

File: cli/webServerlessSpy.ts (hunk 1 above)
Comment (Lewenhaupt) [reply cli/webServerlessSpy.ts:135]: Yeah I must have missed writing it or something cause I did write this before, but I've added it again in cli.ts now. Just did a more thorough check as well and it works.

File: src/ServerlessSpy.ts (hunk 2 above)
Comment (Lewenhaupt) [reply src/ServerlessSpy.ts:106]: But I do realise we do the split in createServerlessSpyListener, so we already have the issue if we change the format. So I'll do it that way instead.

**Comment by Lewenhaupt** [comment]
@markostru Sorry for the confusion, should include all the changes now and I did it with a split instead of a new output since we already do the split in createServerlessSpyListener

**Review by ServerlessLife — APPROVED** [review]
Thank you very much for this fix.
